### ISSUE TITLE
No issue, but question, trying to recreate customer header conditional features

### ISSUE THREAD

**Issue by spudje** [matt8707/kiosk-mode#16]
Great to see a replacement voor custom header!! In its basics it looks great. I have configured it as follows in a yaml file I use as dashboard.

```
views:
  - panel: true
    path: default_view?kiosk
```

With customer header I could actually set different modes per e.g. user, like this:
```
custom_header:
  kiosk_mode: false
  exceptions:
    - conditions:
        user: Wallpanel
      config:
        kiosk_mode: true
```

I would love to have my dashboard use kiosk mode only for Wallpanel user.
Since I'm using yaml mode, creating a new dashboard doesn't make sense, as I will refer to one and the same yaml file for both dashboards.

Can I write some condition check in the dashboard yaml to create the proper view path based on the logged in user?

Thanks a lot for your help!
