### ISSUE TITLE
Why don't we use regular functions?

### ISSUE THREAD

**Issue by KTibow** [matt8707/kiosk-mode#17]
I'm currently working on a PR that adds uglify.js to this. I'm wondering why instead of
```js
function getSidebarElem() {
```
we use
https://github.com/matt8707/kiosk-mode/blob/039fc16d53fbadcff3201e9008c988ab4986cdcf/kiosk-mode.js#L18

**Comment by maykar** [comment]
Just habit I guess. They are the same thing, one is using ES6 arrow functions:

https://www.w3schools.com/js/js_arrow_function.asp

I'll be changing those functions soon anyhow:

I'm currently working on migrating everything over to mutationObservers as right now it's all in a setTimeout and that can be problematic. It's counting on the fact that everything will be rendered in the DOM within 200 milliseconds, when often it's not. If I set kiosk mode now and cache it, then quickly switch between dashboards, occasionally kiosk mode won't activate. On slower systems this would happen more often, like older tablets and devices.

Changing over to mutation observers would guarantee that the elements exist and the styles are inserted as soon as they exist. This would cut down on the time it takes for the header/sidebar to disappear and would only run code when needed.

I'm not sure uglify is really necessary. This is a very small script and if installed with HACS it gets compressed anyhow.

**Comment by maykar** [comment]
Yeah, babel would probably help since this would get used on old devices like wall mounted tablets and it would handle the conversion of any ES6 stuff we're using in there

**Comment by KTibow** [comment]
Any use for GitHub Actions with `git commit --amend`, or do you think only manual running it would be needed?

**Comment by maykar** [comment]
I'd probably do it like https://github.com/custom-cards/boilerplate-card

Make it all automatic on release with actions. Check out the old Custom Header actions as well (not the ones for docs). There was some handy stuff in there like inserting the version number into the console tag automatically, etc.

**Comment by maykar** [comment]
If you're over on the HA discord, feel free to hit me up there. It's quite a bit easier than trying to communicate via issues and PRs

**Comment by KTibow** [comment]
Not on Discord yet, but I wish I was.
Here's what I previously made:
```yaml
name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install uglify-js @babel/core @babel/cli @babel/preset-env
    - run: |
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "GitHub Actions"
        git pull
        mkdir -p dist
        touch dist/kiosk-mode.js
    - run: npx babel kiosk-mode.js --out-file kiosk-mode.js --presets @babel/preset-env
    - run: npx uglify-js kiosk-mode.js -b beautify=false,max_line_len=150 --compress --mangle toplevel --output dist/kiosk-mode.js
    - run: |
        git add dist/kiosk-mode.js
        git commit --amend --no-edit || true
        git push --force || true
```
