### ISSUE TITLE
mobile_settings not effective on iOS app

### ISSUE THREAD

**Issue by Mariusthvdb** [matt8707/kiosk-mode#74]
below config works fine on the entity_settings, but unfortunately I can not get the mobile settings to delete the overflow and
menu button on the iOS companion app 

It does work on a browser window on mobile, and the desktop app, with minimal width the threshold
```
# https://github.com/maykar/kiosk-mode#config-options
mobile_settings:
  hide_menubutton: true
  hide_overflow: true
  ignore_entity_settings: true

entity_settings:
#Hides both the header and sidebar.
  - entity:
      input_select.mode: 'Kiosk'
    kiosk: true
# Hides only the header
  - entity:
      input_boolean.hide_header: 'on'
    hide_header: true
# Hides only the sidebar. Disables swipe to open.
  - entity:
      input_boolean.hide_sidebar: 'on'
    hide_sidebar: true
# Hides only the sidebar menu icon. Does not disable swipe to open.
  - entity:
      input_boolean.hide_menubutton: 'on'
    hide_menubutton: true
# Hides the top right menu
  - entity:
      input_boolean.hide_overflow: 'on'
    hide_overflow: true
```

**Comment by maykar** [comment]
Ah, my familiar nemesis, the iOS companion app. Is it all settings or just `hide_menubutton` & `hide_overflow`? Does modifying the `custom_width` option help at all?

**Comment by Mariusthvdb** [comment]
things started working in the app !

might I ask if it is normal to see a rather large empty space at the bottom of a view? seems much bigger then before (without Kiosk-mode)

secondly: can I add some helpers for mobile_settings too, as under entity_settings. (use case: default behavior would be without the menu button and overflow on mobile, but for that one moment one needs to 'develop' on the go, a boolean could be flipped to get the overflow )

maybe like:
```
mobile_settings:
  hide_overflow: >
    {{states('input_boolean.hide_overflow_mobile')}}
```
hmm is this the way we set templates, as you state in https://github.com/maykar/kiosk-mode#entity_settings ? doesn't even seem to work in the entity_settings like that. must be user error

**Comment by maykar** [comment]
Kiosk mode has no template capabilities and I don't think I'll add any. I'll think on a solution for single settings having the ability to be overridden or not.

**Comment by Mariusthvdb** [comment]
sorry if I misunderstood what you write here:

> For more complex logic use this with a template sensor.

I took that for the possibility to use a template like I posted (and we used in CH...)

nevermind, good to know, wont pursue ;-)

**Comment by maykar** [comment]
Oh, I see. I'm talking about HA's [template sensors](https://www.home-assistant.io/integrations/template/#state-based-template-sensors). I should add that link to the readme

**Comment by Mariusthvdb** [comment]
as an option for the readme:
```
template:

  - binary_sensor:

      - unique_id: mode_kiosk_template
        name: Kiosk mode
        state: >
          {{is_state('input_select.mode','Kiosk') or
            is_state('input_boolean.kiosk_mode','on')}}
```

works like:

```
entity_settings:
#Hides both the header and sidebar.
  - entity:
      binary_sensor.kiosk_mode: 'on'
```
