### ISSUE TITLE
Conditional settings within (non-)admin-settings:

### ISSUE THREAD

**Issue by spudje** [matt8707/kiosk-mode#80]
Should it be possible to do this: (or similar)?

```
kiosk_mode:
  non_admin_settings:
    - entity:
       input_boolean.hide_sidebar: 'on'
       hide_sidebar: true
```

If not, consider this a feature request :)

**Comment by maykar** [comment]
Not able to test ATM and on mobile, but would something like this be what you're looking for?

```
kiosk_mode:
  entity_settings:
     - entity:
         input_boolean.hide_sidebar: 'on'
         hide_sidebar: true
  admin_settings:
    ignore_entity_settings: true
```

If not please give an example of what you're looking to do.
