### ISSUE TITLE
Ignore mobile settings isn't doing anything

### ISSUE THREAD

**Issue by pr0gstar** [matt8707/kiosk-mode#81]
This is part of my Lovelace config but isn't working on my little 7 inch screen with 800x480 resolution. It still shows the side menu.
Using the same user in my browser and changing the browser size to over 800 and something pixels in developer mode the side menu is gone.

Have i done anything wrong or is it a bug and I or some one else could try fixing it?

```
kiosk_mode:
  user_settings:
    - users:
        - hub
      hide_sidebar: true
      ignore_mobile_settings: true
```
