### ISSUE TITLE
Not working on MacOS Chrome

### ISSUE THREAD

**Issue by PrtmPhlp** [matt8707/kiosk-mode#89]
Hey, first thanks for the plugin!
I have the resource added in the configuration and this is my config:
```yaml
title: Home
kiosk_mode:
  admin_settings:
    hide_header: true
    hide_sidebar: true
    hide_overflow: true
  entity_settings:
    - entity:
        input_boolean.hide_sidebar: 'on'
      hide_sidebar: true
    - entity:
        sensor.hide_header: 'on'
      hide_header: true
    - entity:
        input_text.kiosk: 'true'
      kiosk: true
views:
  - title: Clean Home
    path: clean_home
    icon: ''
    theme: noctis
    badges: []
    cards:
      - type: custom:mushroom-chips-card
        chips:
          - type: menu
          - type: weather
            entity: weather.openweathermap
            show_conditions: true
            show_temperature: true
```
I noticed this error in Dev tools:
```
Lovelace config not found, continuing with default configuration.
TypeError: Cannot read properties of undefined (reading 'state')
    at e.value (kiosk-mode.js:32:102)
    at e.value (kiosk-mode.js:20:7)
    at kiosk-mode.js:20:86
```
I configured the dashboard just with the normal UI, so I have no idea, how to fix this and i would appreciate some help.
