### ISSUE TITLE
How to hide the "Search"?

### ISSUE THREAD

**Issue by Photelegy** [matt8707/kiosk-mode#93]
How can I hide the "Search" for specific users without hiding the whole header?

```
kiosk_mode:
  user_settings:
    - users:
        - Guest
      hide_sidebar: true
      hide_header: false
      hide_overflow: true
      hide_menubutton: true
```

Is there something like `hide_search: true` to only hide the search?

![image](https://user-images.githubusercontent.com/61714583/169284106-4a1d309e-0641-42ca-b822-db17cda712de.png)
